---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default